import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-between bg-gray-900 p-4 ">
        <div>
          <Link href="/">
          <div className="text-white text-2xl">
            bit<span className="text-sm">&#9632;</span>a
            <span className="text-sm">&#9632;</span>little
          </div></Link>
        </div>
      </div>
        {children}
      </body>
    </html>
  );
}
